# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7837f0e76d71516a70e29e3f37c12becb554f20150d97d907d5ebd848bd2548f94d290770b9710b476263049884c624c5535b62f1efeaf202454dbff24940966

test:
  secret_key_base: c92c90f4da1e801805ef4e0583a61942ac4451b0d21ccaa15540193e9267192649f5360bddecf90caa0fd74b931c422311f853d2fca5ccc9e344893c2dc60e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
